# Project language
language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

# Allows use container-based infrastructure
sudo: false

# Define an environment variable
env:
  - SYMFONY_VERSION="3.0.*"

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Update composer
before-install:
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml  

before_script: composer install -n

# Run script
script:
  - phpunit