# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.0
      env: SYMFONY_VERSION=2.7.*
    - php: 7.0
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION=3.3.*
    - php: 7.0
      env: SYMFONY_VERSION=3.4.*
    - php: 7.0
      env: DEPENDENCIES=beta
    - php: 7.0
      env: DEPENDENCIES=low
    - php: 7.1
      env: SYMFONY_VERSION=2.8.*
    - php: 7.1
      env: SYMFONY_VERSION=3.3.*
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*
    - php: 7.1
      env: SYMFONY_VERSION=4.0.*
    - php: 7.1
      env: DEPENDENCIES=beta
    - php: 7.1
      env: DEPENDENCIES=low
    - php: 7.2
      env: SYMFONY_VERSION=2.8.*
    - php: 7.2
      env: SYMFONY_VERSION=3.3.*
    - php: 7.2
      env: SYMFONY_VERSION=3.4.*
    - php: 7.2
      env: SYMFONY_VERSION=4.0.*
    - php: 7.2
      env: DEPENDENCIES=beta
    - php: 7.2
      env: DEPENDENCIES=low
    - php: nightly
      env: SYMFONY_VERSION=2.8.*
    - php: nightly
      env: SYMFONY_VERSION=3.3.*
    - php: nightly
      env: SYMFONY_VERSION=3.4.*
    - php: nightly
      env: SYMFONY_VERSION=4.0.*
    - php: nightly
      env: DEPENDENCIES=beta
  allow_failures:
    - php: nightly
    - env: DEPENDENCIES=beta
    - env: DEPENDENCIES=low
    
# Define an environment variable
env:
  - SYMFONY_VERSION="3.0.*" DB=mysql

# Update composer
before-install:
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

# Run script
script:
  - phpunit