# Project language
language: php

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:    
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*    

# Allows use container-based infrastructure
sudo: false

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Update composer
before-install:
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - cp app/config/parameters_prod.yml.dist app/config/parameters_prod.yml  

before_script: composer install -n

# Run script
script:
  - phpunit

deploy:  
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key:
      secure: "$AWS_SECRETACCESSKEY"
    region: "ap-southeast-1"  
    app: "getting-started-symfony-app"
    env: "gettingStarte-symfony-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-229280718428"
    on: 
      branch: master
