easy_admin:

    site_name: 'DinLanka'
    entities:
        Admin:
              label: "Manage Admins"
              class: AppBundle\Entity\Admin
        AirFreight_Orders:
              class: AppBundle\Entity\Air_Freight
        SeaFraight_Orders:
              class: AppBundle\Entity\Sea_Freight