easy_admin:

    site_name: 'DinLanka'
    entities:
        Admin:
              label: "Manage Users"
              class: AppBundle\Entity\Admin
        AirFreight_Orders:
              class: AppBundle\Entity\Air_Freight
        SeaFreight_Orders:
              class: AppBundle\Entity\Sea_Freight
              
        Containers:
              class: AppBundle\Entity\Container
    design:

        brand_color: 'rgba(241, 85, 27, 0.75)'


