easy_admin:

    site_name: 'DinLanka'
    entities:
        Admin:
              label: "Manage Users"
              class: AppBundle\Entity\Fosuser
              list:
                  fields:
                        - id
                        - username
                        - email
                        - lastLogin
              form:
                  fields:
                        - username
                        - email
                        - roles
                        - enabled
                        - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                        - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
        AirFreight_Orders:
              label: "Air Freight"
              class: AppBundle\Entity\Air_Freight

        DinLankaAirFreight_Orders:
              label: "DinLanka Air Freight"
              class: AppBundle\Entity\Dinlanka_air_freight

        SeaFreight_Orders:
              label: "Sea Freight"
              class: AppBundle\Entity\Sea_Freight

        DinLankaSeaFreight_Orders:
              label: "DinLanka Sea Freight"
              class: AppBundle\Entity\Dinlanka_sea_freight
              
        Containers:
              class: AppBundle\Entity\Container
    design:

        brand_color: 'rgba(241, 85, 27, 0.75)'


