#Production Environment parameters : AWS RDS 
parameters:
    database_host: '$RDS_HOSTNAME'
    database_port: '$RDS_PORT'
    database_name: '$RDS_DB_NAME'
    database_user: '$RDS_USERNAME'
    database_password: '$RDS_PASSWORD'  
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt