#Production Environment parameters : AWS RDS 
parameters:
    database_host: aazxoqy1p7v2h3.cq5xph4uv4w7.ap-southeast-1.rds.amazonaws.com
    database_port: 3306
    database_name: ebdb
    database_user: Zangetsu
    database_password: zangetsu
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt